### ISSUE TITLE
Dataset Open-source

### ISSUE THREAD

**Issue by ZixinxinWang** [hrlblab/HATs#2]
Dear authors:
Thanks for your wonderful work! I wonder if and when the data you used to train the model to be packed-up and open-scourced.  Since from your paper, it's large and carefully organized:
![1728894185579](https://github.com/user-attachments/assets/05f1f854-22dd-4c9b-93bc-6d803e859a4c)
And also, I noticed you mentioned that the data would be released once the paper is accpeted. Now that the paper is accepted by CVPR\MICCAI (Congrats), I'm really looking forward to it. Meanwhile this would help other scientists to further investigate in your area. Thanks  for the kindness.

**Comment by ddrrnn123** [comment]
Dear Zixin,

Thank you for your interest! The available human datasets that have been published are as follows:

(1) NEPTUNE dataset for DT, PT, Cap, Tuft, Art, and PTC: http://haeckel.case.edu/data/KI_data/
(2) HuBMAP dataset for MV: https://www.kaggle.com/competitions/hubmap-hacking-the-human-vasculature/overview 

We are working on publishing additional datasets in the future. You may also follow the KPIs challenge (https://sites.google.com/view/kpis2024) for more mouse datasets.

Best regards,
Ruining

**Comment by 06Liz** [comment]
I want to know the structure of dataset

**Comment by 06Liz** [comment]
Q1:File not exists in the reload path: snapshots_2D/EfficientSAM_dynamichead_logits_0201_15class/MOTS_DynConv_EfficientSAM_dynamichead_logits_0201_15class_e50.pth
Q2:train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:167: RuntimeWarning: invalid value encountered in double_scalars
  Val_TPR += TP / (TP + FN)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:167: RuntimeWarning: invalid value encountered in double_scalars
  Val_TPR += TP / (TP + FN)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:167: RuntimeWarning: invalid value encountered in double_scalars
  Val_TPR += TP / (TP + FN)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars
  Val_PPV += TP / (TP + FP)
train_EfficientSAM_HATs.py:167: RuntimeWarning: invalid value encountered in double_scalars
  Val_TPR += TP / (TP + FN)
train_EfficientSAM_HATs.py:3844: RuntimeWarning: invalid value encountered in true_divide
  avg_val_F1 = val_F1 / cnt
train_EfficientSAM_HATs.py:3845: RuntimeWarning: invalid value encountered in true_divide
  avg_val_Dice = val_Dice / cnt
train_EfficientSAM_HATs.py:3846: RuntimeWarning: invalid value encountered in true_divide
  avg_val_TPR = val_TPR / cnt
train_EfficientSAM_HATs.py:3847: RuntimeWarning: invalid value encountered in true_divide
  avg_val_PPV = val_PPV / cnt
Validate 
 0medulla_f1=0.4944 dsc=0.4944 tpr=0.002392 ppv=nan 
 1cortex_f1=nan dsc=nan tpr=nan ppv=nan
 
 2cortexin_f1=nan dsc=nan tpr=nan ppv=nan
 
 3cortexmiddle_f1=nan dsc=nan tpr=nan ppv=nan
 
 4cortexout_f1=nan dsc=nan tpr=nan ppv=nan
 
 5dt_f1=0.5192 dsc=0.468 tpr=nan ppv=nan
 
 6pt_f1=nan dsc=nan tpr=nan ppv=nan
 
 7cap_f1=nan dsc=nan tpr=nan ppv=nan
 
 8tuft_f1=nan dsc=nan tpr=nan ppv=nan
 
 9art_f1=nan dsc=nan tpr=nan ppv=nan
 
 10ptc_f1=nan dsc=nan tpr=nan ppv=nan
 
 11mv_f1=nan dsc=nan tpr=nan ppv=nan
 
 12pod_f1=nan dsc=nan tpr=nan ppv=nan
 
 13mes_f1=nan dsc=nan tpr=nan ppv=nan
 
 14smooth_f1=nan dsc=nan tpr=nan ppv=nan

**Comment by 06Liz** [comment]
@ZixinxinWang Hello, how do you prepare the dataset for training? What is the directory of the dataset? @ddrrnn123

**Comment by ddrrnn123** [comment]
> @ZixinxinWang Hello, how do you prepare the dataset for training? What is the directory of the dataset? @ddrrnn123
We have updated the data structure for the training / testing code. You can download the data from links and organize the data according to the instructions. Please let us know if you have any questions!

Best,
Ruining

**Comment by ddrrnn123** [comment]
> Q1:File not exists in the reload path: snapshots_2D/EfficientSAM_dynamichead_logits_0201_15class/MOTS_DynConv_EfficientSAM_dynamichead_logits_0201_15class_e50.pth Q2:train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:167: RuntimeWarning: invalid value encountered in double_scalars Val_TPR += TP / (TP + FN) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:167: RuntimeWarning: invalid value encountered in double_scalars Val_TPR += TP / (TP + FN) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:167: RuntimeWarning: invalid value encountered in double_scalars Val_TPR += TP / (TP + FN) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:168: RuntimeWarning: invalid value encountered in double_scalars Val_PPV += TP / (TP + FP) train_EfficientSAM_HATs.py:167: RuntimeWarning: invalid value encountered in double_scalars Val_TPR += TP / (TP + FN) train_EfficientSAM_HATs.py:3844: RuntimeWarning: invalid value encountered in true_divide avg_val_F1 = val_F1 / cnt train_EfficientSAM_HATs.py:3845: RuntimeWarning: invalid value encountered in true_divide avg_val_Dice = val_Dice / cnt train_EfficientSAM_HATs.py:3846: RuntimeWarning: invalid value encountered in true_divide avg_val_TPR = val_TPR / cnt train_EfficientSAM_HATs.py:3847: RuntimeWarning: invalid value encountered in true_divide avg_val_PPV = val_PPV / cnt Validate 0medulla_f1=0.4944 dsc=0.4944 tpr=0.002392 ppv=nan 1cortex_f1=nan dsc=nan tpr=nan ppv=nan
> 
> 2cortexin_f1=nan dsc=nan tpr=nan ppv=nan
> 
> 3cortexmiddle_f1=nan dsc=nan tpr=nan ppv=nan
> 
> 4cortexout_f1=nan dsc=nan tpr=nan ppv=nan
> 
> 5dt_f1=0.5192 dsc=0.468 tpr=nan ppv=nan
> 
> 6pt_f1=nan dsc=nan tpr=nan ppv=nan
> 
> 7cap_f1=nan dsc=nan tpr=nan ppv=nan
> 
> 8tuft_f1=nan dsc=nan tpr=nan ppv=nan
> 
> 9art_f1=nan dsc=nan tpr=nan ppv=nan
> 
> 10ptc_f1=nan dsc=nan tpr=nan ppv=nan
> 
> 11mv_f1=nan dsc=nan tpr=nan ppv=nan
> 
> 12pod_f1=nan dsc=nan tpr=nan ppv=nan
> 
> 13mes_f1=nan dsc=nan tpr=nan ppv=nan
> 
> 14smooth_f1=nan dsc=nan tpr=nan ppv=nan

Dear @06Liz ,

We have uploaded both model weights for the PrPSeg model (8-class dataset) and the HATs model (15-class dataset).

Best,
Ruining
